[package]
name = "rsiotmonitor"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.7.1"

# bytes = "0.4.0"
futures-core = "0.3.1"
futures-util = "0.3.1"
log = "0.4.8"

maplit = "1.0.2"
mqtt-async-client = "0.3.1"

rustls = { version = "0.19.0", optional = true }
structopt = "0.3.5"
tokio = { version = "1.24.2", features = ["io-util", "macros", "net", "rt", "process", "rt-multi-thread", "sync", "time"] }
tokio-rustls = { version = "0.22.0", optional = true }

toml-parse = { path="deps/toml-parse" }
webpki-roots = "0.18.0"

nix= "0.26.2"

[features]
default = ["tls"]
tls = ["rustls", "tokio-rustls"]

[profile.release]
opt-level = "z"  # Optimize for size.
codegen-units = 1
panic = "abort"
lto = true
