#[http]
#bind="0.0.0.0"
#port=7880

[mqtt]
serverAddress="mqtt://127.0.0.1:1884"
clientid="iotmonitorfhome2"

[device_esp11]
watchTimeOut=60
helloTopic="home/esp11"
watchTopics="home/esp11/sensors/#"
stateTopics="home/esp11/actuators/#"

[device_esp10]
watchTimeOut=60
helloTopic="home/esp10"
watchTopics="home/esp10/sensors/#"
stateTopics="home/esp10/actuators/#"

[device_esp13]
watchTimeOut=60
helloTopic="home/esp13"
watchTopics="home/esp13/sensors/#"
stateTopics="home/esp13/actuators/#"

[device_esp04]
watchTimeOut=60
helloTopic="home/esp04"
watchTopics="home/esp04/sensors/#"
stateTopics="home/esp04/actuators/#"

[device_esp03]
watchTimeOut=60
helloTopic="home/esp03"
watchTopics="home/esp03/sensors/#"
stateTopics="home/esp03/actuators/#"


[device_esp20]
watchTimeOut=60
helloTopic="home/esp20"
watchTopics="home/esp20/sensors/#"

[device_esp21]
watchTimeOut=60
helloTopic="home/esp21"
watchTopics="home/esp21/sensors/#"

[device_esp22]
watchTimeOut=60
helloTopic="home/esp22"
watchTopics="home/esp22/sensors/#"

[device_esp05]
watchTimeOut=1200
helloTopic="home/esp05"
watchTopics="home/esp05/sensors/#"

[device_esp50]
watchTimeOut=1200
helloTopic="home/esp50"
watchTopics="home/esp50/sensors/#"
stateTopics="home/esp50/actuators/#"

[device_agentnodered]
watchTimeOut=5
helloTopic="home/agents/nodered/watchdog"
watchTopics="home/agents/nodered/#"

